
#Database Configuration Info
LINHCENTRE_SHOPPING_DATABASE_HOST: 'localhost'
LINHCENTRE_SHOPPING_DATABASE_PORT: '3306'
LINHCENTRE_SHOPPING_DATABASE_USER: 'root'
LINHCENTRE_SHOPPING_DATABASE_PASSWORD: ''
LINHCENTRE_SHOPPING_DATABASE_NAME: 'linhcentre_shoping_be_production'
